package com.mattvalli.portfolio.model;

public enum ResourceType {
	WEBSITE_INFORMATIONAL,
	WEBSITE_PROFESSIONAL,
	WEBSITE_ACADEMIC,
	WEBSITE_TUTORIAL,
	WEBSITE_DOCUMENTATION,
	WEBSITE_COMMERCIAL,
	BOOK_PRINT,
	BOOK_DIGITAL,
	BOOK_AUDIO,
	IMAGE_PRINT,
	IMAGE_DIGITAL,
	AUDIO_CLIP,
	AUDIO_SOUNDBITE,
	AUDIO_MUSIC,
	API,
	SDK,
	REFERENCE,
	PRODUCT
}
